In [ ]:
import pandas as pd

print("Pandas is ready")

Pandas is ready

In [ ]:
data = {
    "Name": ["Lakshmi", "Rahul", "Priya", "Rahul", "Anu"],
    "Age": [21, 22, None, 22, 20],
    "Marks": [85, 90, 78, 90, None],
    "City": ["Ballari", "Bengaluru", "Ballari", "Bengaluru", "ballari"]
}

df = pd.DataFrame(data)

df

      Name   Age  Marks       City
0  Lakshmi  21.0   85.0    Ballari
1    Rahul  22.0   90.0  Bengaluru
2    Priya   NaN   78.0    Ballari
3    Rahul  22.0   90.0  Bengaluru
4      Anu  20.0    NaN    ballari

In [ ]:
df.isnull().sum()

Name     0
Age      1
Marks    1
City     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df = df.drop_duplicates()

df

      Name   Age  Marks       City
0  Lakshmi  21.0   85.0    Ballari
1    Rahul  22.0   90.0  Bengaluru
2    Priya   NaN   78.0    Ballari
4      Anu  20.0    NaN    ballari

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df

/tmp/ipykernel_1340/3609200643.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].fillna(df["Age"].mean())
/tmp/ipykernel_1340/3609200643.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

      Name   Age      Marks       City
0  Lakshmi  21.0  85.000000    Ballari
1    Rahul  22.0  90.000000  Bengaluru
2    Priya  21.0  78.000000    Ballari
4      Anu  20.0  84.333333    ballari

In [ ]:
df["City"] = df["City"].str.title()

df

/tmp/ipykernel_1340/3107735569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].str.title()

      Name   Age      Marks       City
0  Lakshmi  21.0  85.000000    Ballari
1    Rahul  22.0  90.000000  Bengaluru
2    Priya  21.0  78.000000    Ballari
4      Anu  20.0  84.333333    Ballari

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      float64
 2   Marks   4 non-null      float64
 3   City    4 non-null      object
dtypes: float64(2), object(2)
memory usage: 160.0+ bytes

In [ ]:
print("Missing values:")
print(df.isnull().sum())

print("Duplicate rows:")
print(df.duplicated().sum())

Missing values:
Name     0
Age      0
Marks    0
City     0
dtype: int64
Duplicate rows:
0

In [ ]:
df.to_csv("cleaned_student_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
df.to_csv("cleaned_student_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

In [ ]:
df = pd.read_excel("DataCleaning_Internship.xlsx")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'DataCleaning_Internship.xlsx'

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_student_data.csv to cleaned_student_data (1).csv

In [ ]:
print(uploaded.keys())

dict_keys(['cleaned_student_data (1).csv'])

In [ ]:
df = pd.read_csv("your_actual_filename.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'your_actual_filename.csv'

In [ ]:
print(uploaded.keys())

dict_keys(['cleaned_student_data (1).csv'])

In [ ]:
df = pd.read_csv("student_data.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'student_data.csv'

In [ ]:
import os
print(os.listdir())

['.config', 'cleaned_student_data.csv', 'cleaned_student_data (1).csv', 'sample_data']

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_student_data (2).csv to cleaned_student_data (2).csv

In [ ]:
df = pd.read_excel("your_actual_filename.xlsx")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'your_actual_filename.xlsx'

In [ ]:
import os
print(os.listdir())

['.config', 'cleaned_student_data (2).csv', 'cleaned_student_data.csv', 'cleaned_student_data (1).csv', 'sample_data']

In [ ]:
import pandas as pd

df = pd.read_excel("student_data.xlsx")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'student_data.xlsx'

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_student_data (3).csv to cleaned_student_data (3).csv

In [ ]:
print(list(uploaded.keys()))

['cleaned_student_data (3).csv']

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

In [ ]:
import pandas as pd
filename = list(uploaded.keys())[0]
df = pd.read_excel(filename)
df.head()

NameError: name 'uploaded' is not defined

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving cleaned_student_data (3).csv to cleaned_student_data (3).csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
import pandas as pd

df = pd.read_csv("cleaned_student_data (3).csv")
df.to_excel("cleaned_student_data.xlsx", index=False)

print("Excel file created successfully!")

Excel file created successfully!

In [ ]:
from google.colab import files
files.download("cleaned_student_data.xlsx")

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("cleaned_student_data.csv")
df.head()

      Name   Age      Marks       City
0  Lakshmi  21.0  85.000000    Ballari
1    Rahul  22.0  90.000000  Bengaluru
2    Priya  21.0  78.000000    Ballari
3      Anu  20.0  84.333333    Ballari

In [ ]:
df.shape

(4, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      float64
 2   Marks   4 non-null      float64
 3   City    4 non-null      object
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe(include="all")

           Name        Age      Marks     City
count         4   4.000000   4.000000        4
unique        4        NaN        NaN        2
top     Lakshmi        NaN        NaN  Ballari
freq          1        NaN        NaN        3
mean        NaN  21.000000  84.333333      NaN
std         NaN   0.816497   4.921608      NaN
min         NaN  20.000000  78.000000      NaN
25%         NaN  20.750000  82.750000      NaN
50%         NaN  21.000000  84.666667      NaN
75%         NaN  21.250000  86.250000      NaN
max         NaN  22.000000  90.000000      NaN

In [ ]:
df.isnull().sum()

Name     0
Age      0
Marks    0
City     0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.isnull().sum()

Name     0
Age      0
Marks    0
City     0
dtype: int64

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [ ]:
df["City"] = df["City"].fillna("Unknown")

In [ ]:
df["City"] = df["City"].str.strip().str.title()

In [ ]:
print("Missing values:")
print(df.isnull().sum())

print("Duplicate rows:")
print(df.duplicated().sum())

print("Cleaned dataset:")
display(df.head())

Missing values:
Name     0
Age      0
Marks    0
City     0
dtype: int64
Duplicate rows:
0
Cleaned dataset:

      Name   Age      Marks       City
0  Lakshmi  21.0  85.000000    Ballari
1    Rahul  22.0  90.000000  Bengaluru
2    Priya  21.0  78.000000    Ballari
3      Anu  20.0  84.333333    Ballari

In [ ]:
df.dtypes

Name      object
Age      float64
Marks    float64
City      object
dtype: object

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

print(df["Age"].dtype)
print(df.head())

float64
      Name   Age      Marks       City
0  Lakshmi  21.0  85.000000    Ballari
1    Rahul  22.0  90.000000  Bengaluru
2    Priya  21.0  78.000000    Ballari
3      Anu  20.0  84.333333    Ballari

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      float64
 2   Marks   4 non-null      float64
 3   City    4 non-null      object
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.isnull().sum()

Name     0
Age      0
Marks    0
City     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
from google.colab import files
files.download("cleaned_dataset.csv")

In [ ]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nCleaned dataset:")
display(df.head())

Missing values:
Name     0
Age      0
Marks    0
City     0
dtype: int64

Duplicate rows:
0

Cleaned dataset:

      Name   Age      Marks       City
0  Lakshmi  21.0  85.000000    Ballari
1    Rahul  22.0  90.000000  Bengaluru
2    Priya  21.0  78.000000    Ballari
3      Anu  20.0  84.333333    Ballari

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!